cube_OBJS = hypercube.o ../common/lp_metric.o main.o helper_cube.o ../common/handle_binary.o\
			../common/hash_function.o binary_string.o handle_output.o ../common/brute_force.o

cube_ARGS = -d ../../MNIST/input.dat -q ../../MNIST/query.dat -k 14 -M 200 -probes 50 -o ../../output/output.txt -N 5 -R 10000

include ../../common.mk