# Κάνοντας compile το <foo>_test.cpp με μια υλοποίηση <foo>.cpp του
# συγκεκριμένου τύπου, παράγουμε ένα test για την υλοποίηση αυτή.

testcube_OBJS = test.o ../common/h.o hypercube.o ../common/metrics.o helper_cube.o

cube_OBJS = ../common/h.o hypercube.o ../common/metrics.o main.o helper_cube.o

# Ο βασικός κορμός του Makefile
include ../../common.mk