# Κάνοντας compile το <foo>_test.cpp με μια υλοποίηση <foo>.cpp του
# συγκεκριμένου τύπου, παράγουμε ένα test για την υλοποίηση αυτή.

testcube_OBJS = test.o ../common/h.o cube.o ../common/metrics.o

# Ο βασικός κορμός του Makefile
include ../../common.mk