graphsearch.so_OBJS = \
					 $(MODULES)/gnn/gnn.o \
					 $(MODULES)/mrng/mrng.o \
					 $(MODULES)/common/directed_graph.o \
					 $(MODULES)/common/generic_search.o \
					 $(MODULES)/handle_output.o \
					 $(MODULES)/../exercise1/A/LSH/lsh.o \
					 $(MODULES)/../exercise1/A/common/lp_metric.o \
					 $(MODULES)/../exercise1/A/common/hash_function.o \
					 $(MODULES)/../exercise1/A/common/brute_force.o \
					 $(MODULES)/../exercise1/A/common/handle_binary.o \
					 $(MODULES)/../exercise1/B/vector_utils.o \
					 $(TESTING)/python_connector.o

include ../common.mk