graphsearch.so_OBJS = \
					 $(MODULES)/approximate_knn_graph/approximate_knn_graph.o \
					 $(MODULES)/mrng/mrng.o \
					 $(MODULES)/nsg/nsg.o \
					 $(MODULES)/common/directed_graph.o \
					 $(MODULES)/common/generic_search.o \
					 $(MODULES)/common/handle_output.o \
					 $(EXERCISE1)/A/LSH/lsh.o \
					 $(EXERCISE1)/A/RandomProjection/hypercube.o \
					 $(EXERCISE1)/A/common/handle_binary.o \
					 $(EXERCISE1)/A/RandomProjection/binary_string.o \
					 $(EXERCISE1)/A/RandomProjection/helper_cube.o \
					 $(EXERCISE1)/A/common/lp_metric.o \
					 $(EXERCISE1)/A/common/hash_function.o \
					 $(EXERCISE1)/A/common/brute_force.o \
					 $(EXERCISE1)/A/common/handle_binary.o \
					 $(EXERCISE1)/B/vector_utils.o \
					 $(TESTING)/python_connector.o

include ../common.mk