# Κάνοντας compile το <foo>_test.cpp με μια υλοποίηση <foo>.cpp του
# συγκεκριμένου τύπου, παράγουμε ένα test για την υλοποίηση αυτή.

lsh_OBJS = main.o lsh.o hash_function.o

# Ο βασικός κορμός του Makefile
include ../../common.mk