shared_lib.so_OBJS = \
					 $(EXERCISE1)/A/LSH/lsh.o \
					 $(EXERCISE1)/A/RandomProjection/hypercube.o \
					 $(EXERCISE1)/A/common/handle_binary.o \
					 $(EXERCISE1)/A/RandomProjection/binary_string.o \
					 $(EXERCISE1)/A/RandomProjection/helper_cube.o \
					 $(EXERCISE1)/A/common/lp_metric.o \
					 $(EXERCISE1)/A/common/hash_function.o \
					 $(EXERCISE1)/A/common/brute_force.o \
					 $(EXERCISE1)/A/common/handle_binary.o \
					 $(EXERCISE1)/B/vector_utils.o \
					 $(EXERCISE1)/B/helper.o \
					 $(EXERCISE1)/B/kmeans.o \
					 $(EXERCISE1)/B/kmeanspp.o \
					 $(EXERCISE2)/source_code/approximate_knn_graph/approximate_knn_graph.o \
					 $(EXERCISE2)/source_code/mrng/mrng.o \
					 $(EXERCISE2)/source_code/nsg/nsg.o \
					 $(EXERCISE2)/source_code/common/directed_graph.o \
					 $(EXERCISE2)/source_code/common/generic_search.o \
					 $(EXERCISE2)/source_code/common/depth_first_search.o \
					 $(EXERCISE2)/source_code/common/handle_output.o \
					 $(TESTING)/nearest_neighbor.o \
					 $(TESTING)/clustering.o

# shared_lib.so_DEFINE += -DNEW

include ../common.mk